[base]

# Greeter used to welcome the user
greeter=/usr/lib/lxdm/lxdm-greeter-gtk

# Default session or desktop used when no systemwide config
session=/usr/bin/openbox-session

[display]

# If show bottom pane
bottom_pane=1

# GTK theme used by greeter
gtk_theme=Clearlooks

# If show keyboard layout select control
keyboard=1

# If show language select control
lang=1

# The theme of greeter
theme=BlackArch

[server]

# Arguments used to start Xserver, not fully function
arg=/usr/bin/X -background vt1

[userlist]

# If disable the user list control at greeter
disable=1
